### ISSUE TITLE
Returning all values if invalid filter value (string)

### ISSUE THREAD

**Issue by TelmoM** [miki725/django-url-filter#64]
I don't know if this is an issue or a feature :) But when the filter value does not exist all the results are returned, for example:
```
/?state=done
# (Returns only the results where the field state is equal to 'done')
/?state=xpto
# (Returns all the results instead of none) (I think this is **not** the expected behaviour)
```
**Note:**
This behaviour does not apply if the field is int, for example id=33 (If 33 does not exist it returns empty).

**Comment by miki725** [comment]
what is the model like? yea it should return no results unless its a choice field or something in which case if you dont use `fail` strict mode, it will ignore all errors

**Comment by TelmoM** [comment]
The field is a ChoiceField. With 'django_filters' it works as expected.
Small Example... 
```
class Order(models.Model):
    STATUSES = (
        ('draft', _('Draft')),
        ('awaiting_approval', _('Awaiting Approval')),
        ('approved', _('Approved')),
        ('on_order', _('On Order')),
        ('order_fulfilled', _('Order Fulfilled')),
    )

    state = models.CharField(max_length=20, choices=STATUSES, default='draft')
    ....
```

**Comment by miki725** [comment]
what happens here is when you send invalid value to a field which is not one of the choices, that field is being ignored altogether which is why you are getting all results. see http://django-url-filter.readthedocs.io/en/latest/api/url_filter.filtersets.base.html#url_filter.filtersets.base.StrictMode

not sure what is a clean approach for these situations. same thing would happen for other fields if you submit invalid data (e.g. `a` for `IntegerField`

maybe add another fail mode which simply does not return any results.

**Comment by TelmoM** [comment]
Yes that's exactly what's happening... Is there any chance you could write a simple example of how to implement the approach you mentioned of adding another fail mode?

**Comment by miki725** [comment]
https://github.com/miki725/django-url-filter/pull/65 should resolve this issue. do you mind giving it a test drive?

p.s. kind of obvious in hindsight. no idea why that was not default behavior since day 1.

**Comment by TelmoM** [comment]
#65 It's working great! 👍 
I still have a questions regarding the behaviour, I try to explain with some examples.
```
/?state__in=done ----> It only returns the "done" results ✅ 
/?state__in=nodone ----> It doesn't return any result because "nodone" is an invalid choice ✅
/?state__in=done,blocked ----> It returns multiple results of "done" and "blocked" ✅
/?state__in=done,nodone ----> It returns no results because "nodone" is causing it to fail, do you think it should return only the "done" results instead of none? ❓
```

**Comment by miki725** [comment]
not sure. it technically breaks validation although `in` is a bit unique. will have to see how it could be handled

**Comment by miki725** [comment]
take another look. should handle it fine now in both `drop` and `empty` modes
